apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron-test
  template:
    metadata:
      labels:
        app: cron-test
    spec:
      containers:
      - name: cron-test
        image: homelab.home:5000/cron-test
        imagePullPolicy: Always
        # ports:
        # - containerPort: 80
        volumeMounts:
          - name: secret-volume
            mountPath: "/etc/secret-test"
            readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: secret-test
