//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "emote")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub twitch_id: String,
  pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::stream_message_emote::Entity")]
  StreamMessageEmote,
}

impl Related<super::stream_message_emote::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::StreamMessageEmote.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
