use clap::{Arg, Command};
use lazy_static::lazy_static;

lazy_static! {
  pub static ref CLAP_ARGS: ClapArgs = ClapArgs::new();
}

pub struct ClapArgs {
  args: clap::ArgMatches,
}

impl ClapArgs {
  const STREAM_REPORT_ID: &'static str = "stream_report_id";
  const GENERATE_FILE_REPORTS: &'static str = "generate_file_reports";

  pub fn new() -> Self {
    let args = Self::setup_args();

    Self { args }
  }

  pub fn report_stream_id(&self) -> i32 {
    let value = self.args.get_one::<String>(Self::STREAM_REPORT_ID).unwrap();

    value.parse::<i32>().unwrap()
  }

  pub fn generate_file_reports(&self) -> bool {
    self.args.get_flag(Self::GENERATE_FILE_REPORTS)
  }

  fn setup_args() -> clap::ArgMatches {
    Command::new("Twitch Chat Parser")
      .arg(
        Arg::new(Self::STREAM_REPORT_ID)
          .short('r')
          .long("report")
          .action(clap::ArgAction::Set)
          .help("Assigns which stream ID from the database to generate a report with."),
      )
      .arg(
        Arg::new(Self::GENERATE_FILE_REPORTS)
          .short('f')
          .long("file-export")
          .action(clap::ArgAction::SetTrue)
          .help("With this flag active, the reports generated by the `database_report_generator` will be exported to files instead of pastebin."),
      )
      .get_matches()
  }
}

impl Default for ClapArgs {
  fn default() -> Self {
    Self::new()
  }
}
