apiVersion: v1
kind: Service
metadata:
  name: twitch-logger-frontend
spec:
  selector:
    app: twitch-logger-frontend
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30010
