//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use super::sea_orm_active_enums::EventType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "donation_event")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub event_type: EventType,
  #[sea_orm(column_type = "Float")]
  pub amount: f32,
  pub timestamp: DateTimeUtc,
  pub donator_twitch_user_id: Option<i32>,
  pub donation_receiver_twitch_user_id: i32,
  pub stream_id: Option<i32>,
  pub subscription_tier: Option<i32>,
  pub unknown_user_id: Option<i32>,
  pub origin_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::gift_sub_recipient::Entity")]
  GiftSubRecipient,
  #[sea_orm(
    belongs_to = "super::stream::Entity",
    from = "Column::StreamId",
    to = "super::stream::Column::Id",
    on_update = "NoAction",
    on_delete = "SetNull"
  )]
  Stream,
  #[sea_orm(
    belongs_to = "super::twitch_user::Entity",
    from = "Column::DonationReceiverTwitchUserId",
    to = "super::twitch_user::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  TwitchUser2,
  #[sea_orm(
    belongs_to = "super::twitch_user::Entity",
    from = "Column::DonatorTwitchUserId",
    to = "super::twitch_user::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  TwitchUser1,
  #[sea_orm(
    belongs_to = "super::unknown_user::Entity",
    from = "Column::UnknownUserId",
    to = "super::unknown_user::Column::Id",
    on_update = "NoAction",
    on_delete = "SetNull"
  )]
  UnknownUser,
}

impl Related<super::gift_sub_recipient::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::GiftSubRecipient.def()
  }
}

impl Related<super::stream::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Stream.def()
  }
}

impl Related<super::unknown_user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UnknownUser.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
