//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "emote_usage")]
pub struct Model {
  pub usage_count: i32,
  #[sea_orm(primary_key, auto_increment = false)]
  pub emote_id: i32,
  #[sea_orm(primary_key, auto_increment = false)]
  pub stream_message_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::emote::Entity",
    from = "Column::EmoteId",
    to = "super::emote::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Emote,
  #[sea_orm(
    belongs_to = "super::stream_message::Entity",
    from = "Column::StreamMessageId",
    to = "super::stream_message::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  StreamMessage,
}

impl Related<super::emote::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Emote.def()
  }
}

impl Related<super::stream_message::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::StreamMessage.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
