//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "gift_sub_recipient")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub recipient_months_subscribed: i32,
  pub twitch_user_id: Option<i32>,
  pub donation_event_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::donation_event::Entity",
    from = "Column::DonationEventId",
    to = "super::donation_event::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  DonationEvent,
  #[sea_orm(
    belongs_to = "super::twitch_user::Entity",
    from = "Column::TwitchUserId",
    to = "super::twitch_user::Column::Id",
    on_update = "NoAction",
    on_delete = "SetNull"
  )]
  TwitchUser,
}

impl Related<super::donation_event::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::DonationEvent.def()
  }
}

impl Related<super::twitch_user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TwitchUser.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
