//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "raid")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub timestamp: DateTimeUtc,
  pub size: i32,
  pub stream_id: Option<i32>,
  pub twitch_user_id: i32,
  pub raider_twitch_user_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::stream::Entity",
    from = "Column::StreamId",
    to = "super::stream::Column::Id",
    on_update = "NoAction",
    on_delete = "SetNull"
  )]
  Stream,
  #[sea_orm(
    belongs_to = "super::twitch_user::Entity",
    from = "Column::RaiderTwitchUserId",
    to = "super::twitch_user::Column::Id",
    on_update = "NoAction",
    on_delete = "SetNull"
  )]
  TwitchUser2,
  #[sea_orm(
    belongs_to = "super::twitch_user::Entity",
    from = "Column::TwitchUserId",
    to = "super::twitch_user::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  TwitchUser1,
}

impl Related<super::stream::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Stream.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
