//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Debug , Clone , PartialEq , Eq , EnumIter , DeriveActiveEnum , Serialize , Deserialize)] # [sea_orm (rs_type = "String" , db_type = "Enum" , enum_name = "event_type")] pub enum EventType { # [sea_orm (string_value = "bits")] Bits , # [sea_orm (string_value = "gift_subs")] GiftSubs , # [sea_orm (string_value = "streamlabs_donation")] StreamlabsDonation , }