//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_type")]
pub enum EventType {
  #[sea_orm(string_value = "bits")]
  Bits,
  #[sea_orm(string_value = "gift_subs")]
  GiftSubs,
  #[sea_orm(string_value = "streamlabs_donation")]
  StreamlabsDonation,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "external_service")]
pub enum ExternalService {
  #[sea_orm(string_value = "twitch")]
  Twitch,
  #[sea_orm(string_value = "seven_tv")]
  SevenTv,
  #[sea_orm(string_value = "bttv")]
  Bttv,
  #[sea_orm(string_value = "franker_face_z")]
  FrankerFaceZ,
}
