//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "stream_message")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub is_first_message: i8,
  pub timestamp: DateTimeUtc,
  pub emote_only: i8,
  #[sea_orm(column_type = "Text", nullable)]
  pub contents: Option<String>,
  pub twitch_user_id: i32,
  pub channel_id: i32,
  pub stream_id: Option<i32>,
  pub is_subscriber: i8,
  #[sea_orm(unique)]
  pub origin_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::emote_usage::Entity")]
  EmoteUsage,
  #[sea_orm(
    belongs_to = "super::stream::Entity",
    from = "Column::StreamId",
    to = "super::stream::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Stream,
  #[sea_orm(
    belongs_to = "super::twitch_user::Entity",
    from = "Column::ChannelId",
    to = "super::twitch_user::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  TwitchUser2,
  #[sea_orm(
    belongs_to = "super::twitch_user::Entity",
    from = "Column::TwitchUserId",
    to = "super::twitch_user::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  TwitchUser1,
}

impl Related<super::emote_usage::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::EmoteUsage.def()
  }
}

impl Related<super::stream::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Stream.def()
  }
}

impl Related<super::emote::Entity> for Entity {
  fn to() -> RelationDef {
    super::emote_usage::Relation::Emote.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::emote_usage::Relation::StreamMessage.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
