//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "twitch_user")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  #[sea_orm(unique)]
  pub twitch_id: i32,
  pub display_name: String,
  pub login_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::gift_sub_recipient::Entity")]
  GiftSubRecipient,
  #[sea_orm(has_many = "super::stream::Entity")]
  Stream,
  #[sea_orm(has_many = "super::twitch_user_name_change::Entity")]
  TwitchUserNameChange,
  #[sea_orm(has_many = "super::twitch_user_unknown_user_association::Entity")]
  TwitchUserUnknownUserAssociation,
}

impl Related<super::gift_sub_recipient::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::GiftSubRecipient.def()
  }
}

impl Related<super::stream::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Stream.def()
  }
}

impl Related<super::twitch_user_name_change::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TwitchUserNameChange.def()
  }
}

impl Related<super::twitch_user_unknown_user_association::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TwitchUserUnknownUserAssociation.def()
  }
}

impl Related<super::unknown_user::Entity> for Entity {
  fn to() -> RelationDef {
    super::twitch_user_unknown_user_association::Relation::UnknownUser.def()
  }
  fn via() -> Option<RelationDef> {
    Some(
      super::twitch_user_unknown_user_association::Relation::TwitchUser
        .def()
        .rev(),
    )
  }
}

impl ActiveModelBehavior for ActiveModel {}
