//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "twitch_user_name_change")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub twitch_user_id: i32,
  pub previous_login_name: Option<String>,
  pub previous_display_name: Option<String>,
  pub new_login_name: Option<String>,
  pub new_display_name: Option<String>,
  pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::twitch_user::Entity",
    from = "Column::TwitchUserId",
    to = "super::twitch_user::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  TwitchUser,
}

impl Related<super::twitch_user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TwitchUser.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
