//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "twitch_user_unknown_user_association")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub unknown_user_id: i32,
  #[sea_orm(primary_key, auto_increment = false)]
  pub twitch_user_id: i32,
  pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::twitch_user::Entity",
    from = "Column::TwitchUserId",
    to = "super::twitch_user::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  TwitchUser,
  #[sea_orm(
    belongs_to = "super::unknown_user::Entity",
    from = "Column::UnknownUserId",
    to = "super::unknown_user::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  UnknownUser,
}

impl Related<super::twitch_user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TwitchUser.def()
  }
}

impl Related<super::unknown_user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UnknownUser.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
