//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "unknown_user")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub name: String,
  pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::donation_event::Entity")]
  DonationEvent,
  #[sea_orm(has_many = "super::twitch_user_unknown_user_association::Entity")]
  TwitchUserUnknownUserAssociation,
}

impl Related<super::donation_event::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::DonationEvent.def()
  }
}

impl Related<super::twitch_user_unknown_user_association::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TwitchUserUnknownUserAssociation.def()
  }
}

impl Related<super::twitch_user::Entity> for Entity {
  fn to() -> RelationDef {
    super::twitch_user_unknown_user_association::Relation::TwitchUser.def()
  }
  fn via() -> Option<RelationDef> {
    Some(
      super::twitch_user_unknown_user_association::Relation::UnknownUser
        .def()
        .rev(),
    )
  }
}

impl ActiveModelBehavior for ActiveModel {}
